---
- hosts: homeassistant
  roles:
    - homeassistant
- hosts: all_running:!jump_host:!homeassistant
  strategy: free
  roles:
    - common
- hosts: proxmox
  roles:
    - proxmox
- hosts: jump_host
  roles:
    - common
- hosts: control_node
  connection: local
  roles:
    - common
