---
# create containers
- hosts: proxmox
  roles:
    - proxmox
# updates
- hosts: all_running:!jump_host:!homeassistant
  # strategy: free
  roles:
    - common
# container-specific config
- hosts: emby
  roles:
    - emby
- hosts: homeassistant
  roles:
    - homeassistant
# update jump_host and control_node separately
- hosts: jump_host
  roles:
    - common
- hosts: control_node
  connection: local
  roles:
    - common
