---
- name: Create MediaWiki LXC
  community.proxmox.proxmox:
    vmid: 501
    api_host: "{{ proxmox_api_host }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_user: "{{ proxmox_api_user }}"
    hostname: wiki
    node: "{{ proxmox_node }}"
    ostemplate: "local:vztmpl/debian-13-standard_13.1-1_amd64.tar.zst"
    password: "{{ root_password }}"
    pubkey: "{{ ssh_public_key }}"
    storage: local-lvm
- name: Define MediaWiki LXC
  community.proxmox.proxmox:
    vmid: 501
    api_host: "{{ proxmox_api_host }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_user: "{{ proxmox_api_user }}"
    features:
      - nesting=1
    hostname: wiki
    memory: 512
    netif:
      net0: "name=eth0,ip=dhcp,ip6=dhcp,bridge=vmbr0"
    node: "{{ proxmox_node }}"
    onboot: true
    ostype: debian
    update: true
- name: Start MediaWiki LXC
  community.proxmox.proxmox:
    vmid: 501
    api_host: "{{ proxmox_api_host }}"
    api_token_id: "{{ proxmox_api_token_id }}"
    api_token_secret: "{{ proxmox_api_token_secret }}"
    api_user: "{{ proxmox_api_user }}"
    node: "{{ proxmox_node }}"
    state: started
  register: start_result
  retries: 5
  until: start_result is success
